POST http://localhost:8000/signup
Content-Type: application/json

{
	"email": "ingo@example.com",
	"firstName": "John",
	"lastName": "Doe",
	"passwordHash": "placeholder"
}

### LOGIN - APPROVED 

POST http://localhost:8000/login
Content-Type: application/json

{
	"email": "testexample107@example.com",
	"passwordHash": "placeholder"

}

