POST http://localhost:8000/signup
Content-Type: application/json

{
	"email": "testexample107@example.com",
	"firstName": "John",
	"lastName": "Doe",
	"passwordHash": "secretpassword"
}

### LOGIN - APPROVED 

POST http://localhost:8000/login
Content-Type: application/json

{
	"email": "testexample303@example.com",
	"passwordHash": "secretpassword",
	"approved": "true"
}

### LOGIN - UNAPPROVED 

POST http://localhost:8000/login
Content-Type: application/json

{
	"email": "testexample107@example.com",
	"passwordHash": "placeholder",
	"approved": "false"
}

