POST http://localhost:8000/users
Content-Type: application/json

{
	"email": "testexample303@example.com",
	"firstName": "John",
	"lastName": "Doe",
	"passwordHash": "placeholder",
	"passwordSalt": "101010101010101"
}

###

GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiMjk5ZWQ1YzgtMGI2Zi00ZmEzLWE2OTMtZDQ0ZDIwOTBhYTZkIiwiZW1haWwiOiJ0ZXN0ZXhhbXBsZTEwN0BleGFtcGxlLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNjUxMDYyNjEyfQ.CtQoIBMpZWNmGCSRmnrMTdNphs2Y3uM1MFqKdpv9QBY
