GET http://localhost:8000/task?due=week

###
GET http://localhost:8000/task?available=true

###

GET http://localhost:8000/task?due=week&available=true


###
POST http://localhost:8000/task
Content-Type: application/json

# {
#     "type": "WEEDING",
#   "deadline": "2022-04-25T00:00:00.000Z",
#   "steps": [] 
# }
{
    "type": "SEEDING",
  "deadline": "2022-04-30T00:00:00.000Z",
  "steps": [] 
}