GET http://localhost:8000/task
Content-Type: application/json

###

GET http://localhost:8000/task?due=week

###
GET http://localhost:8000/task?available=true

###

GET http://localhost:8000/task?due=week&available=true


###
POST http://localhost:8000/task
Content-Type: application/json

{
    "type": "WATERING",
  "deadline": "2022-05-30T00:00:00.000Z",
  "steps": [] 
}